# @title
#Questions Data @title Questions Data
questions = [
    "Do you like steel or brass better?",
    "When are you free?",
    "We have a product like it called [product name] that we just launched, and we were wondering if you’d like to write a review about it.",
    "we were wondering if you’d like to tell us your story.",
    "Not interested anymore?",
    "Have a minute to spare next Wednesday?",
    "Got an extra blanket to fend off the cold in the hills?",
    "Can I ask you about something else?",
    "Please let us know if you are, and we will send you a free sample.",
    "Please let me know if you have any questions or would like a demo.",
    "I’d like to ask, what makes you so sure?",
    "Why don’t you run along home now?",
    "Anything I should know about before we go in tomorrow?",
    "The taxes are done, right?",
    "The plants are all watered?",
    "Any houses in the district that are closing?",
    "Anyone you know in need of help?",
    "Have any diseases I didn't think about?",
    "Any samples affected by my appearance?",
    "Anything else you need to tell me?",
    "Anywhere else work for you?",
    "Anything I should take care of before tomorrow?",
    "Any place I could go to while it's dark in the morning?",
    "Any liars out there in the crowd?",
    "Any pretzels being given out for free tomorrow?",
    "Anyone interested in learning more about this?",
    "Anything else that we gotta talk about?",
    "Any platforms that could work better?",
    "Stopping by Brooklyn sometime soon?",
    "Thinking of striving for that promotion now?",
    "Wondering why I need to do this for you?",
    "Studying the arts lately?",
    "Anywhere safer that I can relocate?",
    "Anytime tomorrow work for you?",
    "Anyone giving you trouble?",
    "Anything new happen in the past few weeks since I was in the office?",
    "Any bees stung by the wilderness?"
    "Anything I can help with before tomorrow?",
    "Any Chipotle bowls give you infection?"
    "I was wondering if the trees are yellow",
    "I was wondering if you need any work to be done on the noble computer",
    "Did you notice they placed “New Ebook” in brackets to gather extra attention?",
    "Do you ever wonder if your life is on the right track?",
    "Do you like to run?",
    "In my case, I have just finished my 3rd year and I would like to know if I can already be considered a 4th-year student.",
    "Could you please tell me if volunteers are offered a room in a shared house?",
    "And if that is so, would you mind telling me if electricity, running water and WIFI are provided?",
    "Do you thrive in the summer?",
    "Would you be available for a quick call to discuss how our services could help you?",
    "Do you appreciate the work I did?",
    "Do you prefer that I stay in Cincinatti?",
    "Did you start on the project?",
    "Did you go running a lot last winter?",
    "Did you like the report I sent over?",
    "Did you get a chance to run over the papers?",
    "Did you already visit my house?",
    "Did you want me to edit your novel?",
    "On top of that, let me know whether the new style for the website is better",
    "Additionally, let us know how you want the cake to be cut",
    "Let me know what you think about the new ideas",
    "Let me know how I can help",
    "Let me know how often you can come to the new place",
    "Let me know what budget you're thinking of for this construction",
    "Let me know how soon you can be at the palace front gates",
    "Let me know why you need fifty books, rather than sixty",
    "Let me know when you need the textbook by",
    "Let me know when you have to be at the coronation ceremony",
    "Let us know how you feel about tackling this project",
    "Let us know how you feel about the military drones attacking America",
    "Let us know whether you think it's dangerous that police are expanding their budget",
    "Let us know whether it's a good idea to go this route",
    "Let us know why we need to move to Las Vegas",
    "I know this is a lot, so let us know if you have any questions",
    "I'm aware that the trees are tall, so let us know if you need extra trimmers",
    "I know this is overwhelming, so let us know if you've got doubts",
    "Let me know if you have recommendations.",
    "Let me know if you have suggestions for this project.",
    "One more question–how much time do you think it will take for you to recover?",
    "Also, how many criminals are watching us right now?",
    "How many water droplets are in the bucket?",
    "How many quotes are in the novel that you wrote for the company?",
    "How many dollars will you pay me if I sue?",
    "How many baskets of elephant statues did he give me?",
    "How much money will you need for this project?",
    "How much money has she given you?",
    "How much water have they wasted?",
    "How much love would they need?",
    "What chores are you taking care of this weekend?",
    "What is the fastest way to get money quick?",
    "What do you need me to do in order to help the process go faster?",
    "What is the best season to go running?",
    "What are steps that I can take to make this easier?",
    "What are you doing that I can brag to your boss about?",
    "Also, what work should I be doing?",
    "Another question I had was, what are the details on this surgery?",
    "Is there any way that we can streamline this?",
    "Is there anything I'm missing?",
    "Finally, is this the right file?",
    "Another doubt I had–is the temperature right in the room?",
    "Additionally, are the pizzas all ready to be picked up in half an hour?",
    "Are we missing any details?",
    "Are you sure the school is safe?",
    "Are we sure that this plan will go as promised?",
    "Are you certain that this is the right method?",
    "Are you sure that the TV is good?",
    "Are you ok?",
    "Are the rockets up and running by now?",
    "Are all plants this green?",
    "Are the buildings secured?",
    "How many times will the ventilator need to be tested?",
    "Can the students handle this much pressure?",
    "Can the teachers take on this project?",
    "Also, can this all be done today?",
    "Can this be done by tomorrow?",
    "Can they have it done by tomorrow?",
    "Can he bake the cookies?",
    "Can he set the clock to a quarter past five on Monday while I work on the treadmill?",
    "Can he cook?",
    "Can she draw?",
    "Can she hold the pan by the handles without burning herself?",
    "Can she work on her novel while screaming?",
    "First, can all of this be done today itself?",
    "Can the buildings develop more quickly?",
    "Can the group get along with each other?",
    "Can the TV show be more diverse than it currently is?",
    "Also, can the trees grow taller than they already are?",
    "To follow up, can the sunglasses turn into something they're not?",
    "Just following up on this–can the database be parsed by Wednesday at 8pm?",
    "Just following up on this–can the servers be refreshed every two weeks under the new company?",
    "Can the knives be made more sharp?",
    "Additionally, can the suppliers cut costs by a fraction?",
    "Along with that, can water grow out of trees?"
    "On top of that, can rovers fly on Mars?",
    "Can the sofas undergo an operation?",
    "Can the pillows become fluffier without losing cushion",
    "Can the plants go another day without being watered?",
    "Can hair clips be blue?",
    "Can nature be colored red?",
    "Can computers think like humans do?",
    "Can they handle this?",
    "Can the mattress turn into a smart mattress?",
    "Can the vase withstand a drop to the ground?",
    "Can man destroy Earth?",
    "Can humanity come together for the war?",
    "Can elephants breed with monkeys?",
    "Can the house withstand these weather conditions?",
    "Could data science be evolved by tomorrow?",
    "Could the cast suffocate your leg?",
    "Could the bed bear the weight of the heavy pillows?",
    "Could math be cooler than water bottles?",
    "Could the colors match each other or is that not possible?",
    "Could the water bottle hold the heat within the water?",
    "Wait, could he cook instead of you?",
    "Will the construction project continue through the winter?",
    "Would it be better if the teachers viewed the project rather than directing it?",
    "One doubt I had–would the gates open by themselves if I shouted the codes?",
    "Would it be nice if I oversaw the flowers?",
    "Would the window blinds be in trouble if too much sunlight infiltrated the house?",
    "Would Alice be mad if I stole her cat?",
    "Would you be grateful if I wrote a note for you?",
    "Would it change things if the ballots were overturned?",
    "Would the sky fall down if it was polluted?",
    "If you address the issues in front of the press, will it make it worse?",
    "Diving off of that question, if you tell the president that he's incapable, will the tornado ensue?"
    "If you break the vase, will she be mad?",
    "If you light the candles, will the fire spread to the bonfire?",
    "If you trim the bushes, will the bushes be too short?",
    "If you water the plants, will the plants be overhydrated?",
    "If you dye the tapestry, is that too much color?",
    "If you sit on the chair, can the chair handle that many people?",
    "If you party all night, would the test still be on Monday?",
    "If you don't like the professor, how many forms do you need to submit to change the class?",
    "If the teachers host a strike, would that affect schools?",
    "During the writer's strike, how many delays have started?",
    "Ever since the pandemic, how many people have gotten COVID?",
    "If the light goes out, how long will it stay out?",
    "If the lab rats break out, how dangerous would that be?",
    "Which resources do you need?",
    "Which of these is the most important for you?",
    "Which color is your favorite out of red, white, and blue?",
    "Which of the seasons is the best to start exercising?",
    "Which doll is the cleanest?",
    "Following up on that, which water bottle would you rather have?",
    "Would you prefer sample topics, a draft outline, or a complete post?",
    "Who do you most need on this project?",
    "Who are your parents?",
    "Who are the best men for this war?",
    "Who is the bride and who is the groom?",
    "Who do you love most?",
    "Also, who are the people in my house?",
    "One more question–who is on the guest list for tonight?",
    "When is the party tonight?",
    "When can you get this project done by?",
    "When do you need my help?",
    "When can you be at my house tonight?",
    "When is the nearest airing of my TV show?",
    "I've been wondering, when can you come?",
    "Also, when will it start?",
    "When will the big group be there?",
    "When are the men coming to Virginia for the competition?",
    "Want more product launch email examples?",
    "Where is the party?",
    "Where are you going to be cooking?",
    "Where are you starting this project?",
    "Would you be interested? ",
    "Where is the best place for me to meet them?",
    "Where should I submit my resume?",
    "Where should I dry the towels?",
    "Along with that, where are the brownies that you baked for me this morning?",
    "Why is the project taking so long?",
    "Why are their data figures so bad?",
    "Why is their class so loud?",
    "Why are you painting the TV?",
    "Why are you breaking the table before putting it back together?",
    "Why does your playlist only have three songs?",
    "Why is the deadline for this task three months from now?",
    "Why does the procedure cost $3000?",
    "Additionally, why can't you restore the data?",
    "Why can't the process use bits instead of bytes?",
    "Please let me know if there’s anything I can help you with to prepare to interview this candidate.",
    "Please let me know where you’re at with the project",
    "Please let me know when is a good time for you to meet so that we can discuss this further.",
    "Does Saturday at 3am work for you?",
    "I will keep you posted and, of course, let me know if there is anything you need help with.",
    "Let me know if you’d like to connect.",
    "Could you please let me know which one you prefer?",
    "Do you ever think about the movie industry?",
    "Please let me know if you would like to promote it."
]

##########


# @title
requests = [
    "And don’t forget to join our Admissions Director for a LIVE webinar Tuesday, August 22nd at 5 pm PST for our Common Application Masterclass!",
    "And run it",
    "Please add them there or share them with us through LastPass.",
    "Please go through it and let me know if you would be interested in working with me.",
    "If you have any questions about the call, just reply to this email.",
    "Could you please click this link and schedule a time and date for our call?",
    "For additional sales outreach email samples that can help you improve lead generation and close more deals, read our guides to Cold email templates and Email subject lines.",
    "Also, talk to Rajna about the problems.",
    "Please follow up with MD loans program.",
    "Use this template to reach out to potential affiliates.",
    "Appreciate them. ",
    "Be concise",
    "Say what you mean immediately.",
    "For example, avoid using terms such as thanks in advance or I look forward to your reply, as it can provide unwanted pressure on an interaction.",
    "Offer them a mechanism to reject your request",
    "Make the request as easy as possible for the other party",
    "Use clear instructions and consider breaking things down into steps.",
    "Use single sentences.",
    "I would appreciate it if you could let me know whether you can accommodate my request.",
    "If you can support my request, please could you provide information by this date?",
    "When you've got the time, could you send me details on the scrum master?",
    "We've got no fixed deadline for the work, but I would appreciate it if you could provide me with the information in the next couple of weeks.",
    "Specifically, I would appreciate it if you could send the following information to me",
    "However, if you are unable to support me in this, please can you identify a suitable person who can?",
    "If you're searching for some inspiration, check out this sample on how to request something from your boss.",
    "Be clear about what you want and why you need it, but maintain respect for their position.",
    "As you know, the project is a priority for us all, so it would be great if you could get this back to me as soon as possible.",
    "Could you spare a few minutes to fill out this form?",
    "Before beginning your email, consider who you're writing to and why.",
    "Think about your relationship with the person and what tone is appropriate. ",
    "Try to make the subject line clear and direct, so the recipient knows what the email is about.",
    "If you could please send me the latest drawings and blueprints at your earliest convenience, we can begin discussing the remaining details.",
    "If you could please take our survey at betterwayshoes.survey.ca, we'd really appreciate it!",
    "You must retain their attention from the first line and get to the point of the email, fast.",
    "Simply maintain the usual courtesies according to your type of request and to whom it is addressed.",
    "When you are requesting something and need to introduce yourself or your company, clearly explain the reason why you’re making the request.",
    "If you could let me know if you can comply with my request, I would appreciate it.",
    "Please confirm that you have received the email.",
    "I know you're busy, but if you could please review the email and get back to me as soon as you can, I'd really appreciate it.",
    "Schedule reminders and follow-up emails so you don’t have to be pursuing your colleagues or clients to complete your request.",
    "As a medical student, I would be very interested in participating in this program, and I would be grateful if you could give me some further details",
    "I would appreciate it if you could tell me whether it is possible to have extended stays since I would like to work in one of your hospitals for a period of over six months.",
    "And deposit it",
    "Please share it with your followers if you feel they will find it useful. ",
    "Then run it on the server",
    "After that, take it to the doctor",
    "Also remember to light the vase",
    "Plus remember to lay the candles",
    "Can you make sure security is in place?",
    "Don’t forget to buy the latest version of the textbook",
    "Please register here.",
    "Please find out how to do the Euclidean process before class.",
    "Buy your Special discounted Combo Tickets Today",
    "Learn your zodiac sign today!",
    "Forward this email so your friends and family can join us for this grand celebration of Garba 2023 in Columbus OH.",
    "Register for the course so that you can learn Python before your interviews",
    "To continue your college journey at Columbus State, follow these steps to update your record",
    "To ensure the safest possible process, continue following the procedure precisely",
    "Submit your final high school transcript to the college",
    "Take care of all necessary details before submitting the document.",
    "Attend a New Student Workshop or meet with an Academic Advisor",
    "Find your true career path or learn how to do so",
    "Check out the senior checklist for other important steps to transition your record.",
    "Apply the vaseline",
    "Review the document to find similar details on how to transition.",
    "Please remember to stop by the pantry during our regular operating hours to pick up your ticket.",
    "Please remember to jump on the rocks three times before proceeding.",
    "So if you are still considering helping out at the tent please sign up.",
    "So if you're considering helping us please go to our website immediately.",
    "If the new time doesn't work for you, message your student to reschedule their lesson.",
    "If this schedule is incompatible, reach out to your director to devise a new one.",
    "Add evite@mailva.evite.com to your address book to ensure that you receive Evite emails in your inbox.",
    "Add our email to your contact list to make sure that you get all of our communications.",
    "If you do not want to receive emails regarding this person's events, block this host. ",
    "If you don't want any more messages from the person, tell them. ",
    "If you suspect you were locked out of your account because of changes made by someone else, you should review & protect your account.",
    "If you think that you didn't deserve this sentence, you should file for an appeal.",
    "If you don't recognize this account, remove it.",
    "If you don't want to face the consequences, exit the premises now",
    "Please click on the button below to view the online sign up sheet.",
    "Please view the link below to check the form.",
    "The awning is a little bulky, so make sure you bring a large enough vehicle.",
    "The church isn't big enough for all, so make sure to bring a car.",
    "If you'd like to manage your Spotify Premium Student plan yourself, you can visit the account management page.",
    "If you would like to edit your plan, you can check out our page.",
    "I am writing to remind you to take the Stanford Admitted Student Survey by using the link below",
    "I'm writing to remind you to jump over the moat when you get to the castle",
    "Simply click one of the links included",
    "Just manage one of the projects included",
    "Get more storage now.",
    "Clarify this to potential clients and customers.",
    "Get more boxes ASAP.",
    "Please respond to this email letting us know if this works for you.",
    "Please respond back to us to let us know whether this works.",
    "Arrive no later than 11:45am so we can start the test on time.",
    "Come by 11 so that we can start working soon.",
    "Please let me know if you have any questions.",
    "Do let the conference know if you have doubts.",
    "Help us stock our shelves so everyone in our community can be fueled for a great summer.",
    "Come help us shop for groceries so that we all can be eating well this Fall.",
    "Take care of my plants while I'm gone in India",
    "Take care of our children while I work in the meeting",
    "I would appreciate it if you helped me find my cat",
    "I would appreciate if you made me a cup of coffee",
    "Whenever you're free, can you teach me how to fly?",
    "Whenever you can, could you show me how to do this step in the project?",
    "I would love if you hit a like on my post",
    "I'd love it if you bought a throw blanket for our housewarming",
    "I would be grateful if you wrote a card for my mom",
    "I'd be so grateful if you told my mom how much we need her to keep trying",
    "Could you tell me how to play the guitar?",
    "Could you tighten the shoelaces on my new boots?",
    "Remind me to give the guitar to the lady",
    "Remind me to tune the strings on the violin before I leave for college",
    "Create a database for children to learn to read",
    "Make a structural pyramid that is fire-proof",
    "I would love it if you could learn how to code",
    "I'd love it if you would double check the security on the house",
    "I would be grateful to you if you showed me how to water the plants",
    "I would be grateful to you if you turned off the faucet",
    "Remember to watch for the clock to turn at midnight",
    "Remember to keep an eye on the guards at the vacation house",
    "Don't forget to fluff the pillows before changing the sheets",
    "Don't forget to report the number of times this incident occurred",
    "Be sure to take care of the dogs while you're at my place.",
    "Be sure to walk off the injury.",
    "Make sure to shred the paper that the information is written on.",
    "Make sure to light the candles with a matchstick.",
    "I'd appreciate it if you looked over the files",
    "I'd appreciate if you watched the cooker",
    "I would appreciate if you walk up the staircase while holding the right rail",
    "I would appreciate if you sold the figures of the books",
    "I'd appreciate it if you dried off the beach towel that got stuck in the rain",
    "It would be very much appreciated if you could stop by this weekend to hand over the papers",
    "It'd be very much appreciated if you ran over the sheet one more time",
    "It would be appreciated if you looked over the documents",
    "It would be appreciated if you worked with me to revise the speech",
    "Confirm the codes before I come home please",
    "Brush your teeth before the dogs run, please",
    "As soon as possible, reply to this email",
    "ASAP, prepare dinner",
    "This is not a joke–you need to file a report now",
    "You need to remove the hair clips from the dryer",
    "You need to dust off the tables",
    "This is serious–you've gotta turn on the lamppost",
    "What I'm about to tell you is very urgent; read this email five times to ensure you learned everything",
    "I have something crucial to tell you; before you learn the codes, ensure that the password is fully encrypted",
    "The TSA is very strict on policy... learn their policy by heart",
    "The ambulance is not always reliable... figure out how to do medical procedures by yourself",
    "I love it when restaurants have great service–make sure that the servers are all kind.",
    "I prefer seating that keeps me next to the water–book cruise tickets that are oceanside.",
    "Now trim the trees",
    "Now find the culprit and frame them",
    "Share Morning Brew with your friends, acquire free Brew swag, and then acquire more friends as a result of your fresh Brew swag.",
    "You should try to write sentences in each job/project with an 'Outcome - Effort' approach.",
    "Can you check all of the things we already did off of the list?",
    "Can you vet through the songs on my playlist?",
    "Can you take care of the kids while I'm gone?",
    "Can you water the plants before I stop by?",
    "Can you take care of the tasks while I'm gone?",
    "Can you sew the curtains into little paterns of mangos?",
    "Can you trim the bushes outside of my house?",
    "Can you make sure that the garden is proper for visitors?",
    "Can you double check the security outside my patio?",
    "Can you paint my nails a different color this Saturday?",
    "Can you make sure the plants are watered?",
    "Also, can you tie my hair into a bun?",
    "Along with that, can you paint the canvas?",
    "I'd love it if you could filter the results",
    "I would love if you could dry the table",
    "Additionally, can you handle the case of the missing acorn?",
    "Just following up on this–can you read over the first draft that I sent last week?",
    "Just following up on this–can you fill out the forms before I go to Canada?",
    "To follow up, can you decide whether you want fairy lights?",
    "Can you make a decision on the project?",
    "Can you take care of the decisions?",
    "Can you forward that email to me?",
    "Can you close the blinds before leaving the beach house?",
    "Can you apply vaseline to any cuts that you see?",
    "Can you write a detailed report on all instances of this situation?",
    "Can you redo the artwork on this album cover?",
    "Can you make a pro con list for whether or not I should enroll in this college?",
    "Can you come to the party a little after the clock turns 3?",
    "Can you read the Cinderella story to Jim as he falls asleep?",
    "Could you write the instructions in my notebook?",
    "Could you teach my children how to read this weekend?",
    "Could you brush up on your piano skills?",
    "Could you replace the light switches in the neighbor's house while I leave for vacation?",
    "Could you polish the brass items around our house?",
    "Could you dust off the furniture before she arrives?",
    "Could you give the cats food tonight?",
    "Could you please turn off the faucet?",
    "Could you light up the fireplace at 8pm tomorrow evening?",
    "Could you wash off the computer screen of the desktop in Amy's room?",
    "Could you ensure that all of the actors have overcome their stage fright?",
    "Tell Jennifer that she needs to sign up for an interview with me.",
    "Fluff the pillows.",
    "Make sure you order before Saturday to get a 20% discount",
    "Click on the button below to visit the checkout page.",
    "Type it all out.",
    "Pat the keyboard 14 times, and then tell the therapist that you're great.",
    "Decide how you want the process to play out.",
    "Figure out how many tries it will take.",
    "Learn what you need to know to score a perfect on the ACT.",
    "Let the dogs into the house",
    "Let the cucumber ripen, and then open it",
    "Be cautious",
    "Let your foot rest this evening",
    "Let the image fully process",
    "Let the hair clips rest in your hair before taking them out",
    "Let the books age on your shelves",
    "Let the cats roam around the patio",
    "Let your head rest this morning",
    "Let your knees relax for some time",
    "To resolve this problem, I would appreciate it if you could provide compensation in the form of a gift voucher or discount on a future meal. ",
    "When sending a cover letter email, make sure you’re using formal language, addressing the right person such as HR or the hiring manager, you use a relevant subject and opening line, and the body of your email demonstrates why you’d be a perfect fit for the job and company.",
    "But regardless of whatever you truly feel, be very careful to only use words that express empathy for whomever it is you’re apologizing to.",
    "Please follow the link to complete a short survey regarding your experience.",
    "Please have a look at the tasks we’ve accomplished below",
    "submit additional proposals if you have others that are aligned with our goals.",
    "Therefore, if you have 5 minutes to spare, please leave your review on our site",
    " As such, we would appreciate it if you could give us 7 minutes of your time to fill out the following survey.",
    "For that reason, we would be super happy if you could fill in our survey!",
    "Also, make sure you include your contact information or a professional email signature that includes your full name, email address and phone number so the customer has multiple ways to get in touch and resolve the issue at hand.",
    "If you cannot confirm your attendance or you have any uncertainties, please let me know.",
    "Sign up with ScholarshipOwl and be applied to their monthly scholarships automatically!",
    "If you know anybody else who’ll find this useful, please forward the email to them.",
    "If you’re unable to access it, just reply to this email and let me know.",
    "And if you need help with a service you offer related to the lead magnet, please check out this page",
    "You should send this email if the person doesn’t open the lead magnet delivery email. ",
    "Could you please take five minutes and fill up this feedback form for us?",
    "Please be honest with your responses.",
    "Write an inviting subject line",
    "Just reveal enough to pique interest and get opens. ",
    "Keep your subject line casual and friendly",
    "Make sure you buy it before the next release",
    "If you have any questions about the product, please respond to this email or use the live chat on the product page.",
    "If possible, set your email automation software to send the email a few days after the product is delivered",
    "But if you want to continue receiving my emails, just click the below link to confirm, and I won’t delete you.",
    "You should tell me before you go outside",
    "If our services interest you, could you please respond to this email and let us know?"
]



########

# @title
nonrequests = [
    "Again, whether a rising senior or a younger student, the best time to start is now!",
    "I want to send you better content",
    "So, you click the subject line to find the answer.",
    "So, I am reaching out to let you know I have the next product for you to promote.",
    "You seem to be doing well at the restaurant",
    "After we work with you, you will be able to secure the connection",
    " I like the products you review here. ",
    "You share a lot of useful tips here.",
    "I would like to contribute a unique post for your blog as well. ",
    "I wanted to let you know I just published a new post on my blog that I am sure you’ll find useful.",
    "You can send the newsletter email every 1 to 4 weeks.",
    "As you can see, it starts with some good personalization.",
    "You can mention this to people you want to invite to your podcast.",
    "It’s because of people like you we have been able to be in business for such a long time.",
    "And I notice that you haven’t opened an email from me in the past",
    "You send this email to re-engage subscribers who have stopped interacting with your emails.",
    "You can also send it if they don’t click the lead magnet link.",
    "It should take you less than three minutes.",
    "And if you have any questions, you can email me at name@example.com or call me",
    "Hope you’ve been enjoying our services so far.",
    "I noticed that you didn’t download the page, so I'm sending it again",
    "I will be happy to interview you at a date and time that is convenient for you.",
    "To see if using something like “new ebook” will help, you will need to conduct your own split test.",
    "As you can see, he was not only tracking my email activity, but also the activity on the video the email directed me to.",
    "You send the product launch email when you want to promote a new product.",
    "I am emailing you today to let you know we have opened doors to our product",
    "Anyone kind knows what I mean by that",
    "Anywhere you go, you won't find a culture like you find in India",
    "Anything you do will help.",
    "Anytime you want or need me, I will always be there for Candace",
    "Anytime the pilgrims are arriving, I'll be sure to support them",
    "Anyone who dares to step up to me is a fool or a leader",
    "Anywhere I go, the group follows me like a bunch of guinea pigs",
    "Anything that the natives want will be granted to them",
    "Any love that has prospered thus far will struggle in the coming years",
    "Any Jack Harlow song could be interpreted as good or bad",
    "Any bumper could be injurious to health if not treated well",
    "Any stars you see tonight are the future of America",
    "Any patio that needs refurnishing should turn towards Auto Insurance",
    "Any crime, including a felony, cannot stop people from running for president.",
    "Anyone that the contruction builders care about is great",
    "Anyways, I love resting",
    "It helps you desribe the problem in more detail",
    "This is the email you send immediately after a new subscriber signs up for your lead magnet.",
    "I’m so glad you signed up for the pillowcases",
    "I have helped several people with this.",
    "Nitro cares about providing you the resources needed to successfully navigate financing college.",
    "I’m emailing you today to let you know we have created a new magnet",
    "We’ll get back to you ASAP and ensure you gain access to it immediately.",
    "In this tool, you'll learn how to tend the leaves",
    "In this post, I have created 21 business email examples with templates that you can swipe to help you kickstart your email marketing immediately.",
    "I wanted to let you know that we just released the Knowledge Bytes podcast and you are featured in the first episode!",
    "It will only take 5 minutes… Promise!",
    "Before we get started, let me give you a brief introduction to our work.",
    "Instead, you’ll ask an open-ended question to elicit data that is harder to measure, like how satisfied (or not) your customers are with your business and why.",
    "As such, you will likely receive fewer results as the questions are more involved and time-consuming to answer.",
    "If you don't want to receive these emails from Spotify in the future, you can edit your profile or unsubscribe.",
    "If your inbox is full, you can remove yourself from our list.",
    "Here, you will not send a survey aimed at capturing quantitative responses",
    "You are probably very busy, I totally understand that!",
    "You can use the following survey email template for formal occasions and adjust it to your needs.",
    "Your answer will be used to help us improve our products and services.",
    "Another doubt I had",
    "If you wait too long before sending it, your readers may no longer remember their experience vividly or may not feel motivated to take time and energy to write a review.",
    "I‘m writing to follow up on my latest email.",
    "Your insights could help many other customers decide whether our products are worth buying.",
    "You will receive tracking information and other details within the next email.",
    "To show our appreciation you will receive Free Shipping on your next order.",
    "You can expect it to arrive at your shipping address within 3 business days.",
    "You can also include a direct payment link that they can click on to easily complete the payment.",
    "Another question I have",
    "You don‘t know me but I know your company very well.",
    "One more question",
    "We are happy to have you join our community.",
    "All our emails will offer valuable information to help you along your journey and we may occasionally recommend a product that we believe in.",
    "Since you will be sending these emails to busy prospects and potential customers, we have added a follow-up email template as well.",
    "Another question",
    "In fact, your company has been my career goal ever since I was in high school.",
    "I know you like to work with the best of the best when it comes to pets",
    "I hate dogs",
    " Let me start by saying that I am a big fan of your work and it has inspired me to push myself beyond what I thought were my limits!",
    "I love the sky",
    "Confirming codes is fun",
    "Applying the solution is terrifying",
    "I knew that you could do it",
    "I always was sure that you knew how do create the table",
    "Love is not the solution",
    "One more doubt",
    "I wanted to follow up",
    "You learn quickly",
    "You are working on this",
    "I am a quick runner",
    "You paint well",
    "You fluff the pillows every night",
    "I appreciate that you stack the books",
    "I love that you read the books",
    "You sew each blanket with care",
    "You help each person see their true potential",
    "You run from trouble",
    "I love that you desire to help others",
    "I am grateful for your desire to help others",
    "I'm thankful for your passion of helping others",
    "The flashing lights are scaring you and the students both.",
    "The pillows are fluffy",
    "Brainstorming essay topics and reviews/edits of drafts.",
    "Working on the “strategic positioning” of applications to maximize chances for admission.",
    "Tickets are selling fast.",
    "It's an event you don't want to miss!",
    "I’m glad we had a chance to discuss your banking needs",
    "Thank you for letting Columbus State be a part of your journey!",
    "A limited quantity is available for this offer - until August 18, 2023 at 10:00 AM PDT or while supplies last",
    "I love you and wanted you to have something special",
    "I wanted to make sure that everyone helping at the information tent has their ticket to get into the event.",
    "You'll need your ticket to get into the festival.",
    "We also have a few slots still open. ",
    "She rescheduled a 60-min Public Speaking lesson with you",
    "19925 Stevens Creek Blvd #100, Cupertino, CA 95014",
    "This timing is not working",
    "Public Speaking lesson rescheduled",
    "Talent and Engagement Specialist",
    "Ashley just messaged you",
    "It is a transactional email, not marketing or promotional, which is why it does not contain an unsubscribe link and why you may be receiving it even if you are unsubscribed from marketing emails.",
    "Other names may be trademarks of their respective owners.",
    "Welcome back to your account",
    "We charged $2 to your card ending in 3456 for your purchase.",
    "One Dublin is having their yearly Back-To School event on Saturday Aug. 12th and we need two volunteers to be there and hand out flyers etc. to families coming to the event. ",
    "Setup starts at 8am, the event starts at 9am, and goes until 1pm.",
    "There is a flyer with more information that you can download from the signup.",
    "You shared so many useful insights there.",
    "I wanted to let you know I run a podcast too.",
    "The event will be in the parking lot of Indian Run Church at 6305 Brand Rd.",
    "One Dublin will also provide refreshments and entertainment at the event. ",
    "Any reservation 8 or more will be on one check with a 20% gratuity. ",
    "Reservations guarantee INDOOR seating only. ",
    "Plans start at $1.99 a month.",
    "I have you scheduled to take the AP Physics 2 exam on Friday, May 12 at 12pm in the Aux Gym. ",
    "I really want to learn how to code.",
    "You are great at listening to my advice",
    "You would look great in a pink sweater",
    "You would make an amazing actress in a musical!",
    "I wonder if she watered the plants",
    "I need to do more in order to get that promotion I deserve",
    "I believe that the best way for you to gain experience is through this role",
    "I would love to see you perform in an act",
    "I'd love to read your book as soon as I get to the library",
    "I can't believe that you would do that to me",
    "I'm so grateful to you for being so kind",
    "I'm grateful to you",
    "Thank you.",
    "I appreciate you!",
    "On top of that, you smile all the time",
    "I'll make sure of it",
    "I always am certain before making a decision",
    "I'm sure it'll be fine",
    "I am absolutely sure that you're the best man for the job",
    "Thanks!",
    "As a reminder, we will indefatigably use one of the words you submitted each day in the Brew",
    "A peek behind the scenes: The most popular words submitted were persnickety, bamboozled, supercalifragilisticexpialidocious, nincompoop, flibbertigibbet, and copacetic.",
    "But none of those is today’s word. ",
    "Stocks started the week on an upswing as tech companies rallied—including Nvidia, whose earnings report investors eagerly await tomorrow—helping the Nasdaq snap a four-day losing streak.",
    "There’s only 1 new car left under $20k",
    "Car-buying wisdom if you’re trying to save money: 'Stick to public transit.'",
    "The humble hatchback may make your mom’s Prius look like a racecar, but its $19,205 average selling price in July really does resemble a mirage in the heat of the auto market.",
    "There’s no place like home—unless there’s a burglar in it. ",
    "It’s comprehensive protection for the whole home, built with breakthrough technologies for faster emergency dispatch.",
    "SimpliSafe’s got ya covered—on multiple fronts, clearly.",
    "Arm gears up for the year’s biggest IPO.",
    "The social media app is looking to sell more than $20 billion in products through TikTok Shop by the end of the year",
    "We haven’t all achieved our supermodel dreams of refusing to get out of bed for less than $10,000 a day, but Americans are demanding more money to start a new job.",
    "Elon desperately wants the world to be saved.",
    "How dating app algorithms decide who you date.",
    "Neal completed the puzzle in 56 seconds—think you can beat that? ",
    "We’re saying we’ll give you free stuff and more friends if you share a link.",
    "Celebrities with initials RR: Rachael Ray, Ronald Reagan, Robert Redford, Ryan Reynolds",
    "Please Note: We've recently updated our Privacy Policy.",
    "Tickets are available now at Patel Brothers",
    "did we mention we will have raffle giveaways for you to partake of as well as send you home with some recipes? ",
    "Offering up our Signature Program - The Dementia Experience with a twist. ",
    "As a reminder, our Key Club meeting is today at 2:45pm in room A108 at Jerome. ",
    "Yes we are a GO for bringing these backpacks",
    "Also we are bringing a bunch of containers of the Easter Eggs we used for the recent Easter Egg hunt",
    "I believe we are all good with myself and Faith to get this stuff to Jerome - we also have the Kiwanis club KeyClub Advisor from Coffman helping also.",
    "This morning I received a listing from one of Dublin Kiwanis club members",
    "It looks like when the members were entered the graduation year was not completed or defaulted to 2023",
    "This tool will display the number of lines in a given text.",
    "The roster has been updated. ",
    "We have five seniors. ",
    "Icing my foot was easy enough, considering that I broke it",
    "You get me laughing so easily",
    "You're absolutely perfect for this role",
    "You love to see me happy!",
    "You bake cookies better than my mom",
    "You're lighting candles in a more efficient way than before",
    "I see that you love to dry towels",
    "We'd love to see you on the dance floor",
    "I'd love to help you achieve your dreams",
    "I would appreciate the chance to watch you perform the musical",
    "I'll be sure to document the whole process",
    "I will make sure that the napkins are all in place–this is an important step for us",
    "This is serious; if we don't recite the tale precisely, people could be angry",
    "I am not joking around–this procedure is vital for our company",
    "This is an easy task!",
    "Sure thing",
    "As soon as possible, the pool manager will clean the area",
    "We won't forget to tell you about the drama when you get back from the area",
    "The event will be on Sunday, March 11 at 12pm",
    "I will let you know as soon as we plan our next meeting at Jerome High School.",
    "I think it will probably be in late March or early April.",
    "Currently, you state a lot of your efforts so the hiring manager understands why you did what you did. ",
    "This looks much better and I appreciate your work.",
    "You are getting almost to the finish line of finalizing your resume.",
    "It might take a little bit more of your time.",
    "Team, obstacles is the way is a wonderful book that we should all read together. ",
    "There are a number of concepts we can learn from that.",
    "I'd love to comprehend what you're saying right now",
    "I'd love to help you see the light",
    "I'd love to help you foam roll",
    "We are all eager to watch the plants grow into huge trees that water the neighborhood and keep the pond full" ,
    "If you ran the test again, I would see different results",
    "If you bounce on the table, it'll break",
    "If you handle the tasks, the todo list will shorten",
    "If you cross the sea, the sea will turn into an ocean",
    "If you run the program, it will be fine",
    "If you consider all edge cases, then there should be no issues",
    "If you handle the surgery, I can too",
    "On top of that, if you put on your sunglasses, then I'll put on my hat",
    "If you're considering surgery, the doctor will take care of you",
    "If you're icing your back, I'll teach you how to do so",
    "Also, if you're controlling the subjects, the rats are the best place to start",
    "If you're watering the garden, I would love to help you",
    "If you love mascots, then you will love my school",
    "I love it when my school holds competitions",
    "I appreciate that my hospital has a jolly spirit",
    "I appreciated the fact that you were there for me when I needed you",
    "I'm grateful to you for dusting off my cabinets",
    "If the risk is low, then I'll be able to take care of it",
    "If expenses are rising, then the team needs to cut some costs",
    "I appreciate that you're taking all factors into account",
    "I appreciate you for cleaning my mattress",
    "I appreciate you for turning my sand into glass",
    "I'm grateful that you wrapped my cast in foil",
    "Also, I'm so grateful that you painted my toenails",
    "Additionally, I appreciate that you reviewed the documents so thoroughly",
    "If you want mashed potatoes, then I'll make them for you",
    "I would like to formally recognize all the hard work and dedication you’ve put into completing the project",
    "Due to your consistent efforts, the project is what it is today and that led to the positive results we were hoping for.",
    "On behalf of Nationwide Insurance, we would like to formally thank you for your hard work and we would like to let you know that we highly value your contribution and your continued dedication to your job.",
    "We are very grateful to have you as a member of our team and we wish to continue to see you thrive within our organization.",
    "I enjoyed speaking with you the other day at the interview for the Software Manager role",
    "The job appears to be an ideal match for my skills, ambitions, and interests.",
    "The innovative approach to the corporate culture within the AI world confirmed my wish to work at your firm.",
    "I will bring my engineering skills, assertiveness, and ability to engage others to work in a cooperative way within the fire department.",
    "Thank you for taking the time to interview me for the insurace overseer at Cummins",
    "I have a high level of interest in working for your firm and look forward to hearing from you.",
    "Best regards, Sam",
    "Dear Hiring Manager",
    "On January 30th, 2020, I made a reservation at your restaurant located at 1234 Mulberry Lane for a birthday dinner for four people.",
    "This letter is intended to bring certain issues to your attention.",
    "Unfortunately, we did not enjoy our dinner due to the fact that the food was very slow to arrive and we received the wrong dishes. ",
    "It’s understandable that it was a busy time at your restaurant, but the quality of the service was not as expected.",
    "I’m looking forward to your reply.",
    "With regards, Tom",
    "It used to be common to send your cover letter and CV as an attachment to your email.",
    "However, it’s becoming a lot more accepted to use the email itself as your cover letter and simply attach your CV.",
    "I was very interested while reading the job posting for the position of Quality assurance.",
    "I’m sure your schedule is very busy, so this email is simply to remind you of your upcoming interview with Jim who is a candidate for data scientists.",
    "The interview will be at 7:30pm on Monday in the gymnasium.",
    "Best, Sam",
    "If things change, you can update your investing goal anytime in Settings.",
    "I would like to update you on what is going on.",
    "Sometimes our mistakes hurt others, cause them discomfort, or make them frustrated.",
    "In these situations, it’s usually the right call to simply apologize.",
    "Apologizing is something that must be sincere or you risk offending the person further.",
    "I want to thank you for bringing these issues to my attention and please know that we are making every effort to correct our mistakes so events like these don’t happen in the future.",
    "I hope to greet you again soon at La Senza",
    "Yours sincerely, Manager",
    "We need to bring buckets and flower garlands to the wedding.",
    "I’m writing to you to express my regret for my behavior on December 20 in regards to the spilled plate",
    "I would like to apologize for my words and actions and reassure you that such an event will not happen again.",
    "On the date in question, I got into a verbal altercation with the head waiter about the scheduling, and this led to my inexcusable behavior. ",
    " I have already apologized to [name of colleague], and I wanted to assure you that I will work to improve my reactions and behavior in the future.",
    "I’d be happy to meet with you to speak about the incident further if you have any outstanding concerns.",
    "I am sorry again.",
    "Regards, Stephanie",
    "I owe you an apology for providing you with the wrong information on August 4 regarding turmoil",
    "It was not my intention to provide inaccurate information and I apologize for any inconvenience it may have caused you.",
    "It wasn’t my intention to mislead you, and it seems the false information was a result of a careless mistake.",
    "I will be sure to be more thoughtful in the future and learn from this incident.",
    "We hope that you will find this proposal helpful and insightful and that it meets your expectations.",
    "Based on an initial estimation, we are happy to offer you a quotation based on your requests. ",
    "As I understand, you offer services to audit businesses’ websites and provide personalized insight into what improvements can be made.",
    " I would like to formally withdraw my candidacy.",
    "However, I would like to sincerely thank you for taking the time to meet with me and for being attentive to my questions about the role. "

]


request_labels = ["request"]
request_labels *= len(requests)

nonrequest_labels = ["nonrequest"]
nonrequest_labels *= len(nonrequests)

question_labels = ["question"]
question_labels *= len(questions)

sentences = requests + nonrequests + questions
labels = request_labels + nonrequest_labels + question_labels
